// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the free extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
using System;

namespace JeffPires.VisualChatGPTStudio
{
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string VisuallChatGPTStudioString = "a8eb0343-b35c-4175-95d8-50549e609ff3";
        public static Guid VisuallChatGPTStudio = new Guid(VisuallChatGPTStudioString);
    }

    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int Complete = 0x0000;
        public const int AddTests = 0x0100;
        public const int FindBugs = 0x0200;
        public const int Optimize = 0x0300;
        public const int OptimizeDiffView = 0x0301;
        public const int Explain = 0x0400;
        public const int AddComments = 0x0500;
        public const int AddSummary = 0x0600;
        public const int AddSummaryForAll = 0x0601;
        public const int AskAnything = 0x0700;
        public const int Translate = 0x0701;
        public const int CustomBefore = 0x0800;
        public const int CustomAfter = 0x0900;
        public const int CustomReplace = 0x0901;
        public const int Cancel = 0x0999;
    }
}