// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by the extension VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace JeffPires.VisualChatGPTStudio
{
    internal sealed partial class Vsix
    {
        public const string Id = "VisuallChatGPTStudio.4854bc98-735d-4622-a0cf-30454b50aa0f";
        public const string Name = "VisuallChatGPTStudio";
        public const string Description = @"Empty VSIX Project.";
        public const string Language = "en-US";
        public const string Version = "1.0";
        public const string Author = "Avanade";
        public const string Tags = "";
    }
}
